### ISSUE TITLE
tine20 2018.08.9 docker container cannot receive emails via TLS

### ISSUE THREAD

**Issue by talsen-team** [talsen-team/docker-app--tine20#1]
**Describe the bug**
Within the tine20 container no emails can be received via TLS using an imap server configuration.

**To Reproduce**
1. Clone the repository master branch  
   `git clone https://github.com/talsen-team/docker-app--tine20.git`
2. Launch the docker container  
   1. `cd docker-app--tine20`
   2. `sudo /bin/bash bash-commands/docker-compose--compose--up.sh . default.docker-compose`
3. Open your browser and open the URL http://localhost
4. Log in as admin with the credentials declared in your [container.env](https://github.com/talsen-team/docker-app--tine20/blob/master/container.env) file
5. Open the tine20 mail application and add an email account using imap configuration with TLS and user authentication 'login' and smtp configuration using TLS and user authentication 'login' as well
6. Now try to fetch the email for the created account, after several seconds an error window pops up containing the message "cannot read - connection closed?". In the volumes/server-tine20/var/log/tine20/tine20.log file the following content can be found here: 
[tine20.log](https://github.com/talsen-team/docker-app--tine20/files/2875888/tine20.log)  
Interesting are the sections from lines 40 to 46 (contains the initial updateFolderCache request) and lines 98 and 99 (contains the error response)  
one other interesting message logged in line 46 shows the following text: `Updating folder cache of parent folder: )` which comes from a logging statement of the file /usr/share/tine20/Felamimail/Controller/Cache/Folder.php:87: 
`        if (Tinebase_Core::isLogLevel(Zend_Log::DEBUG)) Tinebase_Core::getLogger()->debug(__METHOD__ . '::' . __LINE__
            . ' Updating folder cache of parent folder: ' . $_folderName . ')');`  
The log message is strangely formatted with the trailing ')' character.  
The other error logs from line 98 and 99 originally seem to come from the class /usr/share/tine20/vendor/zendframework/zendframework1/library/Zend/Mail/Protocol/Imap.php.  
If the file is modifed by adding a log statement at line 176 in method `_nextLine()`, the log message will show up twice in the tine20 log file (new-tine20.log lines 49 and 50):
[modified--Imap.php.txt](https://github.com/talsen-team/docker-app--tine20/files/2875951/modified--Imap.php.txt)
[new-tine20.log](https://github.com/talsen-team/docker-app--tine20/files/2875948/new-tine20.log)

**Expected behavior**
Email fetching should work.
Is it possible that the localhost http connection gets blocked by the imap TLS connection?

**Screenshots**
Not relevant.

**Logfiles**
Attached above in description.

**Versions**
- docker: Docker version 18.09.2, build 6247962
- repo branch / tag: master
- tine20: 2018.08.9

**Comment by pschuele** [comment]
hm, sounds more like a networking problem.
is it possible to open a telnet connection from the container to the imap server?

**Comment by talsen-team** [comment]
I tried changing the settings a few times. But no success.
Here is another [issue branch](https://github.com/talsen-team/docker-app--tine20/tree/issue--tine20-tls-verification-error) which installs ssmtp into the container and then sends an auto generated mail from inside the container (at least sending mails from inside the container is possible).

Unfortunately I do not have a fully automated ssmtp imap setup which logs into your account, fetches the mails and checks if everything was done correctly, so I did not test if the imap connectivity via another tool from inside the container works.

I just can tell you that much, that we use the gitlab-ce docker container as well, which has the same port mapping to the host and if using the same mail configuration in the gitlab-ce container emails are sent correctly.

Btw the native installation seem to work without further modification, so maybe some package is mssing in the ubuntu:bionic docker image. :S

Can you please work through the issue and confirm that the ssmtp setup works on your machine as well as on mine. Many thanks ;-)

**Comment by pschuele** [comment]
I hope to find some time for this soon - it's been quite busy recently :smile:

**Comment by talsen-team** [comment]
Same at our side :)

I thought about a way to tackle the problem:
In Ubuntu Bionic Server/Desktop the tine package works fine, but not within the docker image.
1. So the first attempt would be to run the [Dockerifle](https://github.com/talsen-team/docker-app--tine20/blob/master/docker/server--tine20/default.docker) commands manually in a clean Server/Desktop installation.
   1. If that works then it could be a missing software-package (like apt-get install command or dpkg package), or
   2. It could be a malformed filesystem (like a missing symbolic link, missing file or similar)

2. The next approach regarding the malformed filesystem would be:
   1. Use the tine20 apt-get installer within docker and check if the same problem arises like the [manual setup](https://github.com/talsen-team/docker-app--tine20/blob/master/docker/server--tine20/default.docker) has. If yes then I would assume a missing software-package, if not
   2. Use the docker diff command to detect all differences created by the apt-get installation (this was initially done to create this [manual setup](https://github.com/talsen-team/docker-app--tine20/blob/master/docker/server--tine20/default.docker)) and embed those changes bit by bit into the [manual setup](https://github.com/talsen-team/docker-app--tine20/blob/master/docker/server--tine20/default.docker). If the problem persists I would assume a missing software-package.

3. The next approach for the possibly missing software-package would be:
   1. Install all differentiating apt-get packages in the docker image (like all what the Server / Desktop has installed extra). If that does not work, then
   2. Install all dpkg packages in the docker image (if there are any differences to the apt-get result). If that does not work as well, then I would assume a malformed filesystem.

What do you think about these next steps?

**Comment by talsen-team** [comment]
The issue seems to be resolved with version v2019.02.4 of tine20.
Receiving / sending mails works for me now, when configuring the following (we are using 1und1.de as mail account provider):
![tine20-setup-configuration](https://user-images.githubusercontent.com/40595118/56078967-10fb1200-5dee-11e9-91c1-046e831ba748.png)
![tine20-account-configuration](https://user-images.githubusercontent.com/40595118/56078970-13f60280-5dee-11e9-9830-7b54e4ab7f51.png)
I turned the 'Verify peer Certificate' option off, and in the setup for IMAP maybe the SSL can be selected the same way as in the account configuration :)
@pschuele can you please try out configuring an email account with the v2019.02.4 docker image and double-check if it works now? Thank you!!

**Comment by pschuele** [comment]
I'm sorry, but I still had no time to have a deeper look at your docker image. but it's still on my todo list. so I'll check email, too when I review https://github.com/tine20/tine20/issues/6993

**Comment by talsen-team** [comment]
FYI: No hurry about that. We are currently using the prepared docker image, also (manually) tested version upgrades and various tine20 features. Everything works as expected. The only thing missing for now is an adequate ansible role + infrastructure tests, but for now I'm still not quite sure how deep the testing requirements should go.

**Comment by pschuele** [comment]
ok, thanks for the update.

we are currently working on a gitlab-ci setup with docker images. you can have a look at it here -> https://github.com/tine20/tine20/tree/master/ci

**Comment by talsen-team** [comment]
Mh. Thanks for the info about your testing approach :). Tbh I did not use the GitLab CI job configuration this extensively, currently I only used Travis CI which boots a virtual machine, on which the docker instances and docker networks can be created using e.g. a docker-compose yaml configuration file and the docker-compose up / down CLI commands.
This is also why I initially (for myself) thought about an ansible + molecule + testinfra approach, because Travis CI provides the ideal basis for that (the ansible driver docker can easily interact with docker containers and molecule automatically creates / destroys testing candidates).
But nice to see that GitLab CI also has an approach for that.

How is the container cleanup handled by GitLab, are the extra services automatically disposed after each pipline execution, because we maybe also want to extend our GitLab CI knowledge in the direction of infrastructure testing / staging, ...?

Thx 4 your help!!

**Comment by byteplow** [comment]
Extra services are bound to one job, not the hole pipeline. All containers and services belonging to a job are disposed after the job finishes. You have to clean up the pictures yourself. We use temporary vms. Pushed images will be deleted by the registry after some time.

The pipelines are configured in a yaml file. It is possible to reuse configuration with yaml anchors and merges. Or with a nice but functional the same gitlab "commands". If we need more complicated logic we use shell scripts which get called by the jobs.
